apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: {{ include "todo-app.name" . }}-backend
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "todo-app.name" . }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8000