apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: {{ include "todo-app.name" . }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
  cohere-api-key: {{ .Values.secrets.cohereApiKey | b64enc | quote }}