apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: todo-app
    ai-monitored: "true"
type: Opaque
data:
  # Database configuration
  database-url: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpuUGdfaEFYZk03b04xcHFWQGVwLWVtcHR5LXJlY2lwZS1haGwwdGVoeC1wb29sZXIuYy0zLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU=

  # JWT and Auth configuration
  secret-key: TGxpMGthb2kxTjJsNFVFcFRpd0swV2F1WE92bWUySUs=

  better-auth-secret: TGxpMGthb2kxTjJsNFVFcFRpd0swV2F1WE92bWUySUs=

  # AI Provider configuration
  cohere-api-key: NzQ4aUJNUjRZZkRaWDZaZmlvSWJQSnBrcHRBM2ZsQ2Q2NFJyaTFiSQ==